[package]
name = "td"
version = "0.1.0"
authors = ["StrixVaria"]
edition = "2018"

[dependencies]
piston = "0.48.0"
piston2d-graphics = "0.32.0"
piston2d-opengl_graphics = "0.65.0"
pistoncore-sdl2_window = "0.62.0"
rand = "0.6.5"
float-cmp = "0.5.0"
names = "0.10.0"